spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        # 路由ID（一个路由配置一个ID）
        - id: lock-redis
 
          # 通过注册中心来查找服务（lb代表从注册中心获取服务，并且负载均衡）
          uri: lb://lock-redis/
 
          # 匹配到的以/api/customer/开头的路径都转发到order的服务，相当于访问 lb://ORDER/**
          predicates:
            - Path=/api/uuredislock/**
          # 去掉匹配到的路径的前2级 这里也就是 /api/customer
          filters:
            - StripPrefix=2
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
server:
  port: 12000
  
  
eureka:
#客户端
  client:
#注册中心地址
    service-url:
      defaultZone: http://eureka:dsp@13.228.36.167:1999/eureka/
      
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
    hostname: localhost
